let CollectDate = {
  "code": 0,
  "msg": "OK:[200]",
  "data": {
    "data": {
      "total": 4,
      "per_page": 15,
      "current_page": 1,
      "last_page": 1,
      "next_page_url": null,
      "prev_page_url": null,
      "from": 1,
      "to": 4,
      "data": [
        {
          "id": 1,
          "buy_id": 0,
          "goods_id": 1,
          "price": "500.00",
          "addon_id": 7,
          "created_at": "2016-06-01 15:56:24",
          "updated_at": "2016-06-01 15:56:24",
          "deleted_at": null,
          "goods": {
            "id": 1,
            "user_id": 1,
            "snum": "1",
            "title": "1",
            "description": "1",
            "goods_images": "1",
            "content": "1",
            "made_by": "1",
            "deliver_address": "1",
            "discount": 1,
            "fare": "1.00",
            "brokerage": 1,
            "expire": 1,
            "maintain": 255,
            "stock": 50,
            "is_activity": "0",
            "activity_ids": null,
            "is_legal": "0",
            "created_at": null,
            "updated_at": null,
            "deleted_at": null
          },
          "goods_addon": {
            "id": 7,
            "goods_id": 1,
            "parent_id": 6,
            "feature_main": "",
            "feature_sub": "红色",
            "goods_price": "500.00",
            "stock": 50,
            "created_at": "2016-06-01 10:54:20",
            "updated_at": null,
            "deleted_at": null,
            "parent_addon": {
              "id": 6,
              "goods_id": 1,
              "parent_id": 0,
              "feature_main": "38码",
              "feature_sub": "",
              "goods_price": "0.00",
              "stock": 0,
              "created_at": "2016-06-01 10:54:00",
              "updated_at": null,
              "deleted_at": null
            }
          }
        },
        {
          "id": 2,
          "buy_id": 0,
          "goods_id": 1,
          "price": "500.00",
          "addon_id": 7,
          "created_at": "2016-06-02 09:03:39",
          "updated_at": "2016-06-02 09:03:39",
          "deleted_at": null,
          "goods": {
            "id": 1,
            "user_id": 1,
            "snum": "1",
            "title": "1",
            "description": "1",
            "goods_images": "1",
            "content": "1",
            "made_by": "1",
            "deliver_address": "1",
            "discount": 1,
            "fare": "1.00",
            "brokerage": 1,
            "expire": 1,
            "maintain": 255,
            "stock": 50,
            "is_activity": "0",
            "activity_ids": null,
            "is_legal": "0",
            "created_at": null,
            "updated_at": null,
            "deleted_at": null
          },
          "goods_addon": {
            "id": 7,
            "goods_id": 1,
            "parent_id": 6,
            "feature_main": "",
            "feature_sub": "红色",
            "goods_price": "500.00",
            "stock": 50,
            "created_at": "2016-06-01 10:54:20",
            "updated_at": null,
            "deleted_at": null,
            "parent_addon": {
              "id": 6,
              "goods_id": 1,
              "parent_id": 0,
              "feature_main": "38码",
              "feature_sub": "",
              "goods_price": "0.00",
              "stock": 0,
              "created_at": "2016-06-01 10:54:00",
              "updated_at": null,
              "deleted_at": null
            }
          }
        },
        {
          "id": 3,
          "buy_id": 0,
          "goods_id": 1,
          "price": "500.00",
          "addon_id": 7,
          "created_at": "2016-06-02 09:16:30",
          "updated_at": "2016-06-02 09:16:30",
          "deleted_at": null,
          "goods": {
            "id": 1,
            "user_id": 1,
            "snum": "1",
            "title": "1",
            "description": "1",
            "goods_images": "1",
            "content": "1",
            "made_by": "1",
            "deliver_address": "1",
            "discount": 1,
            "fare": "1.00",
            "brokerage": 1,
            "expire": 1,
            "maintain": 255,
            "stock": 50,
            "is_activity": "0",
            "activity_ids": null,
            "is_legal": "0",
            "created_at": null,
            "updated_at": null,
            "deleted_at": null
          },
          "goods_addon": {
            "id": 7,
            "goods_id": 1,
            "parent_id": 6,
            "feature_main": "",
            "feature_sub": "红色",
            "goods_price": "500.00",
            "stock": 50,
            "created_at": "2016-06-01 10:54:20",
            "updated_at": null,
            "deleted_at": null,
            "parent_addon": {
              "id": 6,
              "goods_id": 1,
              "parent_id": 0,
              "feature_main": "38码",
              "feature_sub": "",
              "goods_price": "0.00",
              "stock": 0,
              "created_at": "2016-06-01 10:54:00",
              "updated_at": null,
              "deleted_at": null
            }
          }
        },
        {
          "id": 4,
          "buy_id": 1,
          "goods_id": 1,
          "price": "500.00",
          "addon_id": 7,
          "created_at": "2016-06-03 11:10:42",
          "updated_at": "2016-06-03 11:10:42",
          "deleted_at": null,
          "goods": {
            "id": 1,
            "user_id": 1,
            "snum": "1",
            "title": "1",
            "description": "1",
            "goods_images": "1",
            "content": "1",
            "made_by": "1",
            "deliver_address": "1",
            "discount": 1,
            "fare": "1.00",
            "brokerage": 1,
            "expire": 1,
            "maintain": 255,
            "stock": 50,
            "is_activity": "0",
            "activity_ids": null,
            "is_legal": "0",
            "created_at": null,
            "updated_at": null,
            "deleted_at": null
          },
          "goods_addon": {
            "id": 7,
            "goods_id": 1,
            "parent_id": 6,
            "feature_main": "",
            "feature_sub": "红色",
            "goods_price": "500.00",
            "stock": 50,
            "created_at": "2016-06-01 10:54:20",
            "updated_at": null,
            "deleted_at": null,
            "parent_addon": {
              "id": 6,
              "goods_id": 1,
              "parent_id": 0,
              "feature_main": "38码",
              "feature_sub": "",
              "goods_price": "0.00",
              "stock": 0,
              "created_at": "2016-06-01 10:54:00",
              "updated_at": null,
              "deleted_at": null
            }
          }
        }
      ]
    }
  }
}
module.exports = CollectDate
